/* tslint:disable */
/* eslint-disable */
/**
 * IVAO Brasil
 * API pública da IVAO Brasil
 *
 * OpenAPI spec version: 1.0.0
 * Contact: br-web@ivao.aero
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { FlightPlan } from '../models';
/**
 * RoutesApi - axios parameter creator
 * @export
 */
export const RoutesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Real Flight plans for a given route
         * @param {string} dep 
         * @param {string} dest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        routesDepDestGet: async (dep: string, dest: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'dep' is not null or undefined
            if (dep === null || dep === undefined) {
                throw new RequiredError('dep','Required parameter dep was null or undefined when calling routesDepDestGet.');
            }
            // verify required parameter 'dest' is not null or undefined
            if (dest === null || dest === undefined) {
                throw new RequiredError('dest','Required parameter dest was null or undefined when calling routesDepDestGet.');
            }
            const localVarPath = `/routes/{dep}/{dest}`
                .replace(`{${"dep"}}`, encodeURIComponent(String(dep)))
                .replace(`{${"dest"}}`, encodeURIComponent(String(dest)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoutesApi - functional programming interface
 * @export
 */
export const RoutesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Real Flight plans for a given route
         * @param {string} dep 
         * @param {string} dest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async routesDepDestGet(dep: string, dest: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FlightPlan>>> {
            const localVarAxiosArgs = await RoutesApiAxiosParamCreator(configuration).routesDepDestGet(dep, dest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RoutesApi - factory interface
 * @export
 */
export const RoutesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get Real Flight plans for a given route
         * @param {string} dep 
         * @param {string} dest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        routesDepDestGet(dep: string, dest: string, options?: any): AxiosPromise<Array<FlightPlan>> {
            return RoutesApiFp(configuration).routesDepDestGet(dep, dest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoutesApi - object-oriented interface
 * @export
 * @class RoutesApi
 * @extends {BaseAPI}
 */
export class RoutesApi extends BaseAPI {
    /**
     * 
     * @summary Get Real Flight plans for a given route
     * @param {string} dep 
     * @param {string} dest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoutesApi
     */
    public routesDepDestGet(dep: string, dest: string, options?: any) {
        return RoutesApiFp(this.configuration).routesDepDestGet(dep, dest, options).then((request) => request(this.axios, this.basePath));
    }
}
