/* tslint:disable */
/* eslint-disable */
/**
 * IVAO Brasil
 * API pública da IVAO Brasil
 *
 * OpenAPI spec version: 1.0.0
 * Contact: br-web@ivao.aero
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AirportChartsInfoAtcs
 */
export interface AirportChartsInfoAtcs {
    /**
     * 
     * @type {string}
     * @memberof AirportChartsInfoAtcs
     */
    connectionCallsign?: any;
    /**
     * 
     * @type {string}
     * @memberof AirportChartsInfoAtcs
     */
    radioCallsignPortuguese?: any;
    /**
     * 
     * @type {string}
     * @memberof AirportChartsInfoAtcs
     */
    radioCallsignEnglish?: any;
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof AirportChartsInfoAtcs
     */
    frequencies?: any;
}
