/* tslint:disable */
/* eslint-disable */
/**
 * IVAO Brasil
 * API pública da IVAO Brasil
 *
 * OpenAPI spec version: 1.0.0
 * Contact: br-web@ivao.aero
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AirportChartsInfoThresholds
 */
export interface AirportChartsInfoThresholds {
    /**
     * 
     * @type {string}
     * @memberof AirportChartsInfoThresholds
     */
    rwy?: any;
    /**
     * 
     * @type {number}
     * @memberof AirportChartsInfoThresholds
     */
    tora?: any;
    /**
     * 
     * @type {number}
     * @memberof AirportChartsInfoThresholds
     */
    toda?: any;
    /**
     * 
     * @type {number}
     * @memberof AirportChartsInfoThresholds
     */
    asda?: any;
    /**
     * 
     * @type {number}
     * @memberof AirportChartsInfoThresholds
     */
    lda?: any;
}
