/* tslint:disable */
/* eslint-disable */
/**
 * IVAO Brasil
 * API pública da IVAO Brasil
 *
 * OpenAPI spec version: 1.0.0
 * Contact: br-web@ivao.aero
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AirportChartsIvaoData
 */
export interface AirportChartsIvaoData {
    /**
     * 
     * @type {any}
     * @memberof AirportChartsIvaoData
     */
    rwyConfiguration?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof AirportChartsIvaoData
     */
    rmk?: any;
}
