/* tslint:disable */
/* eslint-disable */
/**
 * IVAO Brasil
 * API pública da IVAO Brasil
 *
 * OpenAPI spec version: 1.0.0
 * Contact: br-web@ivao.aero
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AirportChartsInfoNavaids
 */
export interface AirportChartsInfoNavaids {
    /**
     * 
     * @type {string}
     * @memberof AirportChartsInfoNavaids
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof AirportChartsInfoNavaids
     */
    thr?: any;
    /**
     * 
     * @type {string}
     * @memberof AirportChartsInfoNavaids
     */
    icao?: any;
    /**
     * 
     * @type {number}
     * @memberof AirportChartsInfoNavaids
     */
    freq?: any;
}
