/* tslint:disable */
/* eslint-disable */
/**
 * IVAO Brasil
 * API pública da IVAO Brasil
 *
 * OpenAPI spec version: 1.0.0
 * Contact: br-web@ivao.aero
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FlightPlanInner
 */
export interface FlightPlanInner {
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    validSince?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    validUntil?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    days?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    callsign?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    acft?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    dep?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    eobt?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    spd?: any;
    /**
     * 
     * @type {number}
     * @memberof FlightPlanInner
     */
    fl?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    route?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    dest?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    eet?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    rmk?: any;
    /**
     * 
     * @type {string}
     * @memberof FlightPlanInner
     */
    logo?: any;
}
