/* tslint:disable */
/* eslint-disable */
/**
 * IVAO Brasil
 * API pública da IVAO Brasil
 *
 * OpenAPI spec version: 1.0.0
 * Contact: br-web@ivao.aero
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PreferentialRouteResponseDep
 */
export interface PreferentialRouteResponseDep {
    /**
     * 
     * @type {string}
     * @memberof PreferentialRouteResponseDep
     */
    dep?: any;
    /**
     * 
     * @type {string}
     * @memberof PreferentialRouteResponseDep
     */
    dest?: any;
    /**
     * 
     * @type {string}
     * @memberof PreferentialRouteResponseDep
     */
    route?: any;
    /**
     * 
     * @type {string}
     * @memberof PreferentialRouteResponseDep
     */
    airspace?: any;
    /**
     * 
     * @type {string}
     * @memberof PreferentialRouteResponseDep
     */
    rmk?: any;
}
