/* tslint:disable */
/* eslint-disable */
/**
 * IVAO Brasil
 * API pública da IVAO Brasil
 *
 * OpenAPI spec version: 1.0.0
 * Contact: br-web@ivao.aero
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PreferentialRouteResponseRoutes
 */
export interface PreferentialRouteResponseRoutes {
    /**
     * 
     * @type {Array&lt;PreferentialRouteResponseDep&gt;}
     * @memberof PreferentialRouteResponseRoutes
     */
    dep?: any;
    /**
     * 
     * @type {Array&lt;PreferentialRouteResponseDep&gt;}
     * @memberof PreferentialRouteResponseRoutes
     */
    dest?: any;
}
