/* tslint:disable */
/* eslint-disable */
/**
 * IVAO Brasil
 * API pública da IVAO Brasil
 *
 * OpenAPI spec version: 1.0.0
 * Contact: br-web@ivao.aero
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TrainingSession
 */
export interface TrainingSession {
    /**
     * 
     * @type {number}
     * @memberof TrainingSession
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof TrainingSession
     */
    rating?: TrainingSessionRatingEnum;
    /**
     * 
     * @type {string}
     * @memberof TrainingSession
     */
    type?: TrainingSessionTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof TrainingSession
     */
    occurrenceDate?: any;
    /**
     * 
     * @type {string}
     * @memberof TrainingSession
     */
    local?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum TrainingSessionRatingEnum {
    ADC = 'ADC',
    ACC = 'ACC',
    SEC = 'SEC'
}
/**
    * @export
    * @enum {string}
    */
export enum TrainingSessionTypeEnum {
    EXAM = 'EXAM',
    TRAINING = 'TRAINING'
}

